### ISSUE TITLE
Update QR Code to support xPortal app login

### ISSUE THREAD

**Issue by ionutmiftode** [xdevguild/nextjs-dapp-template#23]
After the update from yesterday the login with the xPortal app (ex Maiar) stoped working

**Comment by juliancwirko** [comment]
Hi, unfortunately. You can read more info here: https://twitter.com/xPetrvs/status/1630668060733349908

The update was planned anyway, but I never thought that xPortal would drop support for WC1, especially since the Wallet Connect provider, which supports WC2, is still in beta version: https://github.com/multiversx/mx-sdk-js-wallet-connect-provider/tree/providerV2

The next steps would be:
1. prepare for an update
2. hopefully, the MultiversX team will bring back support for WC1 in xPortal, at least for some time, the same as it was in the Maiar app

**Comment by juliancwirko** [comment]
implemented through https://github.com/useElven/core
